In [2]:
import faiss
import numpy as np

In [4]:
d = 64					# dimension of vector
num_total = 10000		# number of total vectors
num_query = 5			# number of query vectors

np.random.seed(1234)             # make reproducible

total_vectors = np.random.random((num_total, d)).astype('float32')
query_vectors = np.random.random((num_query, d)).astype('float32')

In [5]:
Index = faiss.IndexFlatL2(d)
print(Index.is_trained)		# True
Index.add(total_vectors)	# add 연산
print(Index.ntotal)		# 10000

True
10000


In [6]:
k=3
distances, indexes = Index.search(query_vectors, k)

print(distances)	# num_query x k
# [[7.011895  7.390568  7.478056 ]
#  [8.265501  8.38073   9.07618  ]
#  [7.980177  8.24932   8.45091  ]
#  [8.033938  8.254479  8.498654 ]
#  [7.9609275 8.029879  8.259771 ]]
print(indexes)
# [[ 72  84 160]
#  [ 13  26   2]
#  [101  68  76]
#  [ 49 152  18]
#  [ 41  51 199]]

[[5.0900974 5.670616  5.7184644]
 [6.858701  6.956443  7.08839  ]
 [5.2772083 5.4527187 5.796511 ]
 [5.809805  6.0942507 6.1004057]
 [5.14467   5.5545816 5.785306 ]]
[[1204 3271 2568]
 [8063 2700  919]
 [3919 8653 4130]
 [4429  230  317]
 [9103  199 6044]]


In [7]:
distances, indexes = Index.search(total_vectors[:5], k)

print(distances)
# [[0.        7.8548703 8.563642 ]
#  [0.        7.848359  7.9348636]
#  [0.        7.3042192 7.663117 ]
#  [0.        7.7451077 8.46536  ]
#  [0.        7.7310977 8.006843 ]]
print(indexes)
# [[  0  78  39]
#  [  1  24  88]
#  [  2  13 101]
#  [  3  18   8]
#  [  4  18  52]]

[[0.        5.9857316 6.005853 ]
 [0.        5.5655904 5.7691574]
 [0.        5.665924  5.6770835]
 [0.        5.7480383 6.273041 ]
 [0.        5.4505696 5.6836843]]
[[   0 5325 7124]
 [   1 3549  555]
 [   2  304 5103]
 [   3 5425 8762]
 [   4 8984 8897]]
